name: final_project_mobile_app_flutter
description: Cactask, Management tasks and employees for small company, By the developer Muhmad Omar Haj Hmdo.

publish_to: 'none'
version: 1.2.31+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  firebase_auth: ^4.2.10
  firebase_analytics: ^10.2.0
  awesome_dialog: ^3.2.1
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/logo.png"


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/icon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700